#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const readline = require("readline");

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

console.log("🌍 HustlersHub - Worldcoin Configuration Setup\n");

function askQuestion(question) {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer);
    });
  });
}

async function setup() {
  console.log(
    "This script will help you configure your Worldcoin integration.\n"
  );

  console.log("📋 Before continuing, make sure you have:");
  console.log("   1. Created an account at https://developer.worldcoin.org/");
  console.log("   2. Created a new app in the Developer Portal");
  console.log(
    '   3. Set up an Incognito Action with ID: "hustlershub-verification"'
  );
  console.log(
    "   4. Noted your App ID (format: app_staging_xxxxx or app_xxxxx)\n"
  );

  const continueSetup = await askQuestion("Ready to continue? (y/n): ");

  if (
    continueSetup.toLowerCase() !== "y" &&
    continueSetup.toLowerCase() !== "yes"
  ) {
    console.log("Setup cancelled. Run this script again when you're ready!");
    rl.close();
    return;
  }

  console.log("\n🔧 Configuration:");

  const appId = await askQuestion("Enter your Worldcoin App ID: ");

  if (!appId || !appId.startsWith("app_")) {
    console.log('❌ Invalid App ID format. Should start with "app_"');
    rl.close();
    return;
  }

  // Create .env.local file
  const envContent = `# Worldcoin App Configuration
# Generated by setup script on ${new Date().toISOString()}
APP_ID=${appId}

# Your app is configured! 
# Start the development server with: pnpm dev
# Open in World App for full functionality
`;

  const envPath = path.join(process.cwd(), ".env.local");

  try {
    fs.writeFileSync(envPath, envContent);
    console.log("\n✅ Configuration saved to .env.local");
    console.log("\n🚀 Next steps:");
    console.log("   1. Run: pnpm dev");
    console.log("   2. Open http://localhost:3000 in World App");
    console.log("   3. Test wallet connection and World ID verification");
  } catch (error) {
    console.log("❌ Error writing configuration file:", error.message);
  }

  rl.close();
}

setup().catch(console.error);
